site_name: Jão's Blog

plugins:
  - git-revision-date
  - search
  - glightbox
  - enumerate-headings:
      toc_depth: 3
      exclude:
        - index.md
        
theme:
  name: material
  language: pt-BR
  font:
    text: Noto Serif
  icon:
    logo: material/bird
  features:
    - navigation.top
  palette:
    - scheme: slate
      primary: deep purple

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js