INHERIT: nav.yml

watch:
  - nav.yml

site_name: Jão's Blog
repo_url: https://github.com/joaodanil0?tab=repositories

# plugins:
#   - glightbox
#   - search

extra_css:
  - style.css
  
theme:
  name: material
  language: pt-BR
  font:
    text: Noto Serif
  icon:
    logo: material/bird
  features:
    - navigation.top
    - content.code.copy
  palette:
    - scheme: slate
      primary: deep purple
  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - pymdownx.arithmatex
  #     generic: true
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_div_format

# extra_javascript:
#   - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js